"use client";
import { useState } from 'react';
import { Clock3, Copy, Check, Users, MessageSquare, Calendar, X, Sparkles } from 'lucide-react';
const chapters=['The pause','The real cost','Another way','The brief','Your call'];
export default function Home(){
 const [step,S]=useState(0),[people,P]=useState(5),[minutes,M]=useState(30),[outcome,O]=useState(''),[context,C]=useState(''),[reason,R]=useState(''),[decision,D]=useState(''),[copied,K]=useState('');
 const copy=async(text:string,key:string)=>{try{await navigator.clipboard.writeText(text);K(key);setTimeout(()=>K(''),2200)}catch{K('Unable to copy. Please select and copy the text.')}};
 const summary=`${decision==='meet'?'Let’s have a focused meeting.':'Let’s handle this asynchronously.'}\n\nDesired outcome: ${outcome}\nContext: ${context}\nWhy live discussion might help: ${reason||'Not needed'}\n${decision==='meet'?`Proposed timebox: ${Math.min(minutes,30)} minutes. Invite only the people needed to reach the outcome.`:'Next step: share the context and request a written response with a clear deadline.'}`;
 return <main><header><a className="brand" href="/" aria-label="Before we meet home"><span className="mark"><X size={19}/></span> before we meet<span className="brand-dot">.</span></a><button className="share" onClick={()=>copy(window.location.origin,'link')}><Copy size={15}/>{copied==='link'?'Link copied':'Copy link'}</button></header>
 <div className="shell"><aside><span className="eyebrow">A LITTLE SPACE TO THINK</span><nav aria-label="Slides">{chapters.map((c,i)=><button key={c} className={step===i?'active':''} onClick={()=>{if(i<4||outcome.trim()&&context.trim())S(i)}}><span>{String(i+1).padStart(2,'0')}</span>{c}{i<step&&<Check size={15}/>}</button>)}</nav><div className="side-note"><Clock3 size={17}/><span>A two-minute pause.<br/>A more intentional workday.</span></div></aside>
 <section className="deck" aria-label={chapters[step]}><div className="deck-top"><span>THE MEETING CHECK</span><span>{String(step+1).padStart(2,'0')} / 05</span></div><div className="slide" key={step}>
 {step===0&&<><div className="pill"><span/> Before the calendar invite</div><h1>Could this be<br/><em>a message?</em></h1><p className="lead">Your time matters. So does theirs.<br/>Let’s take a moment to see what this conversation really needs.</p><div className="time-visual"><div className="time-block">FOCUS TIME<div className="wave">{Array.from({length:27},(_,i)=><i key={i} style={{height:`${18+Math.sin(i*.7)*12}px`,animationDelay:`${i*.045}s`}}/>)}</div></div><div className="interrupt"><Calendar size={18}/><span>“Quick sync?”</span><span className="duration">30 min</span></div><div className="time-block after">GETTING BACK INTO IT<div className="dashes"/></div></div><div className="caption">A meeting takes a slot. An interruption breaks the flow.</div></>}
 {step===1&&<><div className="pill">01 / Time adds up</div><h1>Thirty minutes.<br/><em>For everyone.</em></h1><p className="lead">The calendar shows one slot. The team gives up the combined time.</p><div className="calculator"><div className="calc-input"><label htmlFor="people">People <strong>{people}</strong></label><input id="people" type="range" min="2" max="20" value={people} onChange={e=>P(+e.target.value)}/><label htmlFor="minutes">Minutes <strong>{minutes}</strong></label><input id="minutes" type="range" min="15" max="90" step="15" value={minutes} onChange={e=>M(+e.target.value)}/></div><div className="total"><span>{(people*minutes/60).toFixed(1)}</span><div>team hours</div><small>{people} people × {minutes} minutes<br/>Before preparation or follow-up.</small></div></div></>}
 {step===2&&<><div className="pill">02 / Try a smaller move</div><h1>Move the work.<br/><em>Not the calendar.</em></h1><p className="lead">Give people something concrete to respond to, and time to think.</p><div className="alternatives"><article><MessageSquare/><span>SHARE AN UPDATE</span><h3>Write it down.</h3><p>What changed, what’s blocked, and what you need next.</p></article><article><Sparkles/><span>GET A DECISION</span><h3>Make a proposal.</h3><p>Share the options, your recommendation, and a response deadline.</p></article><article><Users/><span>UNTANGLE A PROBLEM</span><h3>Show the thing.</h3><p>Link the design, code, or example. Ask one specific question.</p></article></div><p className="small-note">A live conversation can still help with sensitive topics, urgent blockers, or difficult tradeoffs.</p></>}
 {step===3&&<><div className="pill">03 / Make it concrete</div><h1>What do you<br/><em>need to leave with?</em></h1><p className="lead compact">A clear brief helps, whichever route you choose.</p><div className="brief"><label htmlFor="outcome">What outcome do you need? <span>Required</span></label><input id="outcome" maxLength={500} value={outcome} onChange={e=>O(e.target.value)} placeholder="e.g. Agree which checkout approach to build"/><label htmlFor="context">What should people know first? <span>Required</span></label><textarea id="context" maxLength={2000} value={context} onChange={e=>C(e.target.value)} placeholder="Share context, a proposal, or a link to the work."/><label htmlFor="reason">What would live discussion help resolve? <span>Optional</span></label><input id="reason" maxLength={500} value={reason} onChange={e=>R(e.target.value)} placeholder="e.g. Two teams need to work through a tradeoff"/></div><div className="caption">Your answers stay in this tab. Nothing is submitted.</div></>}
 {step===4&&<><div className="pill">04 / Your time, your call</div><h1>{decision?'A clearer':'Do we still'}<br/><em>{decision?'next step.':'need to meet?'}</em></h1>{!decision?<><p className="lead">You know the situation best. Choose what moves the work forward.</p><div className="choices"><button onClick={()=>D('async')}><MessageSquare/><strong>Let’s do this async</strong><span>Send the brief. Give people time to respond.</span></button><button onClick={()=>D('meet')}><Calendar/><strong>Yes, let’s meet</strong><span>Keep it small, focused, and timeboxed.</span></button></div></>:<><div className="result"><span className="result-label"><Check size={16}/>{decision==='meet'?'A focused meeting':'An async conversation'}</span><p className="summary">{summary}</p><button className="primary" onClick={()=>copy(summary,'brief')}><Copy size={16}/>{copied==='brief'?'Copied':'Copy reply'}</button><button className="text-button" onClick={()=>D('')}>Change my choice</button></div><p className="caption">Paste this reply into the conversation. No invitation or message has been sent.</p></>}</>}
 </div><div className="deck-bottom"><button className="back" disabled={step===0} onClick={()=>S(step-1)}>Back</button><div className="progress" aria-label={`Slide ${step+1} of 5`}>{chapters.map((c,i)=><i className={i<=step?'done':''} key={c}/>)}</div>{step<4?<button className="primary" disabled={step===3&&(!outcome.trim()||!context.trim())} onClick={()=>S(step+1)}>{step===0?'Take the two-minute check':step===3?'Make the call':'Continue'}</button>:<button className="back" onClick={()=>{S(0);D('')}}>Start again</button>}</div></section></div>
 <footer><span>Fewer meetings. Better conversations.</span><a href="https://basecamp.com/gettingreal/07.3-meetings-are-toxic" target="_blank" rel="noreferrer">Inspired by Basecamp’s Getting Real</a></footer><div role="status" className="sr-only">{copied==='link'?'Link copied':copied==='brief'?'Reply copied':copied}</div></main>
}
